# Generated by Django 6.0.2 on 2026-02-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_headline', models.CharField(default='Built on Trust, Driven by Innovation', max_length=200)),
                ('our_story', models.TextField(default='Founded with a vision to bridge the gap between security and technology...')),
                ('mission', models.TextField(default='To provide world-class security and technology solutions...')),
                ('vision', models.TextField(default='To be the most trusted name in security technology...')),
                ('projects_completed', models.PositiveIntegerField(default=500)),
                ('happy_clients', models.PositiveIntegerField(default=200)),
                ('years_experience', models.PositiveIntegerField(default=10)),
                ('team_members_count', models.PositiveIntegerField(default=50)),
            ],
            options={
                'verbose_name_plural': 'Company Info',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(default='fa-star', max_length=100)),
                ('color_class', models.CharField(default='primary', help_text='Tailwind color prefix: primary, accent, green, yellow, etc.', max_length=50)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(default='fa-check', help_text='Font Awesome icon class', max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order', 'title'],
            },
        ),
    ]
