# Generated by Django 6.0.2 on 2026-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyinfo_corevalue_whychooseus'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default='Accra, Ghana', max_length=255),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default='info@kelstechsystems.com', max_length=254),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile or page URL'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='+233 XX XXX XXXX', max_length=50),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter profile URL'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='233XXXXXXXXX', help_text='Include country code without +, e.g. 233XXXXXXXXX', max_length=30),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='working_hours',
            field=models.CharField(default='Mon - Fri: 8AM - 6PM', max_length=100),
        ),
    ]
