# Generated by Django 6.0.2 on 2026-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Global SEO description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Global SEO title (max 60 chars)', max_length=60),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Default image for social sharing', null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 60 chars)', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image for social sharing', null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 60 chars)', max_length=60),
        ),
        migrations.AddField(
            model_name='service',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image for social sharing', null=True, upload_to='seo/'),
        ),
    ]
