# Generated by Django 6.0.2 on 2026-03-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_full_description_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='footer_description',
            field=models.TextField(default='Empowering businesses with cutting-edge security solutions and innovative technology services.', help_text='Brief description shown in the website footer'),
        ),
    ]
