# Generated by Django 6.0.2 on 2026-03-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companyinfo_footer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Main website logo', null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(default='Kels Technologies & Systems', help_text='Name displayed on the website', max_length=100),
        ),
    ]
