# Generated by Django 6.1 on 2026-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companyinfo_company_logo_companyinfo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='brochure',
            field=models.FileField(blank=True, help_text='Upload company brochure PDF or document for the floating download button', null=True, upload_to='brochures/'),
        ),
    ]
